name: Deploy Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  HUGO_VERSION: "0.147.3" # https://github.com/google/docsy/blob/main/package.json
  DOCSY_VERSION: "v0.11.0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["aileron-foo"]
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt -y update
          sudo apt -y install \
            bison \
            build-essential \
            cmake \
            curl \
            flex \
            fonts-lyx \
            graphviz \
            default-jre \
            libcairo2-dev \
            libffi-dev \
            libgdk-pixbuf2.0-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libxml2-dev \
            pkg-config \
            ruby \
            ruby-dev \
            libwebp-dev \
            libzstd-dev
          sudo gem install bundler
          sudo bundle install
          npm install -g @mermaid-js/mermaid-cli
      - run: |
          sudo chmod +x ./test.sh
          PROJECT="${{ matrix.project }}" ./test.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}
          path: ./static/${{ matrix.project }}

  hugo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - uses: actions/download-artifact@v4
      - name: install hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb
          sudo snap install dart-sass
      - name: install npm packages
        run: |
          # Install required https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/.
          # npm install --save-dev autoprefixer
          # npm install --save-dev postcss-cli
          # npm install --save-dev postcss
          npm install
          cd themes/docsy/ && git fetch --tags && git checkout tags/${DOCSY_VERSION}
          cd themes/docsy/ && npm install
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --minify
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: hugo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
